name: Tests

on:
  workflow_dispatch:
  push:
  
  
jobs:
  run-test:
    runs-on: macos-14
    name: Build debug version of the app
    env:
      NSUnbufferedIO: YES # display xcodebuild output in the correct order for github action log
    steps:
    - name: Dump GitHub vars
      env:
        GITHUB_VARS: ${{ toJson(vars) }}
      run: echo "$GITHUB_VARS"
    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - uses: actions/checkout@v3
    - name: Unit Specs
      uses: sersoft-gmbh/xcodebuild-action@v3.2
      with:
        project: CoreTest/CoreTest.xcodeproj
        scheme: CoreTest
        destination: platform=macOS
        action: test
